[text]
0x03d740 = "fn shop_main(_: u32)"

0x0759e0 = "fn set_flag(flag: u32, value: bool) -> bool"
0x07b100 = "fn reset_all_items()" # maybe
0x07bcf0 = "fn aquire_main_weapon(main_weapon_id: u32)"
0x07bd30 = "fn aquire_sub_weapon(sub_weapon_id: u32, amount: u32)"
0x07c020 = "fn acquire_item(item_id: u32)"
0x07c2a0 = "fn acquire_rom(rom_id: u32)"
0x07d620 = "fn reset_equipments()" # maybe

0x080da0 = "'load_save_data" # unknown
0x08deb0.0x0000 = "fn game_tick(unknown: *const ()) -> *const ()"
0x08deb0.0x0543 = "'call_unknown_for_on_game_tick" # func(param as *const ());
0x08f940 = "fn reset_all_items_flags()" # maybe
0x091660.0x0000 = "fn init(unconfirmed: *const ()) -> *const ()"
0x091660.0x0007 = "'push_script_dat_ref_path"
0x0b0f00 = "fn load_script(path: *const c_char)"
0x0b797a.0x0000 = "fn load_script_sub_routine(unconfirmed: *const ()) -> *const ()"
0x0b797a.0x01ac = "'call_create_file_a"

[data]
0x0bb04c = "create_file_a: *const ()"
0x0cc748 = "flags: *mut Flags"

0x0d9e61 = "f6: u8"
0x0d9e62 = "f7: u8"
0x0d9e70 = "items: [u8; 60]"
0x0d9eb6 = "coin: u16"
0x0d9eec = "shuriken: u16" # max 255

0x0e5f0c = "weight: u16"
0x0e5f7c = "num_of_key_presses: u32"

0x0e6658 = "pause: u32"
0x0e6680 = "unknown_walk_speed_base_multiple: u32" # * 0x0124
0x0e66a0 = "game_state: u32" # 0: foreground, -2: background, -3: paused
0x0e66a4 = "f6_2: u32"
0x0e6800 = "field: ()"
0x0e6bd0 = "room_number: ()"

0x3a8e1c = "unknown_walk_speed_base_addr: ()"
